import fs from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import readline from "node:readline/promises";
import { chromium } from "playwright";

const DEFAULT_URL = "https://www.douyin.com/";
const DEFAULT_OUTPUT = path.resolve("cookies", "douyin.txt");
const DEFAULT_PROFILE = path.resolve("cookies", "browser-profile");

function parseArgs(argv) {
  const args = {
    url: DEFAULT_URL,
    output: DEFAULT_OUTPUT,
    profile: DEFAULT_PROFILE,
    channel: "msedge",
  };

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    const next = argv[index + 1];
    if (arg === "--url" && next) {
      args.url = next;
      index += 1;
    } else if (arg === "--output" && next) {
      args.output = path.resolve(next);
      index += 1;
    } else if (arg === "--profile" && next) {
      args.profile = path.resolve(next);
      index += 1;
    } else if (arg === "--channel" && next) {
      args.channel = next === "bundled" ? undefined : next;
      index += 1;
    } else if (arg === "--help" || arg === "-h") {
      printHelp();
      process.exit(0);
    }
  }

  return args;
}

function printHelp() {
  console.log(`Usage:
  npm run export:cookies -- --url https://www.douyin.com --output .\\cookies\\douyin.txt

Options:
  --url       Page to open before exporting cookies. Default: ${DEFAULT_URL}
  --output    Netscape cookies.txt output path. Default: ${DEFAULT_OUTPUT}
  --profile   Browser profile folder used by this helper. Default: ${DEFAULT_PROFILE}
  --channel   Browser channel, such as msedge or chrome. Use bundled for Playwright Chromium.`);
}

function escapeCookieValue(value) {
  return String(value ?? "").replace(/\r?\n/g, "");
}

function toNetscapeCookie(cookie) {
  const httpOnlyPrefix = cookie.httpOnly ? "#HttpOnly_" : "";
  const domain = `${httpOnlyPrefix}${cookie.domain}`;
  const includeSubdomains = cookie.domain.startsWith(".") ? "TRUE" : "FALSE";
  const secure = cookie.secure ? "TRUE" : "FALSE";
  const expires = cookie.expires && cookie.expires > 0 ? Math.floor(cookie.expires) : 0;

  return [
    domain,
    includeSubdomains,
    cookie.path || "/",
    secure,
    expires,
    escapeCookieValue(cookie.name),
    escapeCookieValue(cookie.value),
  ].join("\t");
}

async function launchContext(options) {
  const launchOptions = {
    headless: false,
    viewport: { width: 1280, height: 860 },
    locale: "zh-CN",
  };

  if (options.channel) {
    launchOptions.channel = options.channel;
  }

  return chromium.launchPersistentContext(options.profile, launchOptions);
}

async function main() {
  const options = parseArgs(process.argv.slice(2));
  await fs.mkdir(path.dirname(options.output), { recursive: true });
  await fs.mkdir(options.profile, { recursive: true });

  let context;
  try {
    context = await launchContext(options);
  } catch (error) {
    if (options.channel) {
      console.warn(`Could not launch ${options.channel}, trying bundled Chromium instead.`);
      context = await launchContext({ ...options, channel: undefined });
    } else {
      throw error;
    }
  }

  const page = context.pages()[0] || await context.newPage();
  await page.goto(options.url, { waitUntil: "domcontentloaded" });

  console.log("\nA browser window is open.");
  console.log("Log in to Douyin in that window if needed, then return here and press Enter.");

  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
  await rl.question("\nPress Enter after login is complete...");
  rl.close();

  const cookies = await context.cookies();
  const lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by scripts/export_cookies.mjs",
    ...cookies.map(toNetscapeCookie),
    "",
  ];

  await fs.writeFile(options.output, lines.join("\n"), "utf8");
  await context.close();

  console.log(`\nSaved ${cookies.length} cookies to: ${options.output}`);
  console.log("Use it with:");
  console.log(`python .\\video_to_text.py "VIDEO_URL" --language zh --model tiny --cookies "${options.output}"`);
}

main().catch((error) => {
  console.error("\nFailed to export cookies.");
  console.error(error?.message || error);
  console.error("\nIf bundled Chromium is missing, run:");
  console.error("npx playwright install chromium");
  process.exit(1);
});
