from __future__ import annotations

import asyncio
import json
import os
import shutil
import uuid
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any

from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.responses import FileResponse, HTMLResponse
from fastapi.staticfiles import StaticFiles

from video_to_text import extract_url, process_media


BASE_DIR = Path(__file__).resolve().parent
OUTPUT_DIR = BASE_DIR / "outputs"
UPLOAD_DIR = BASE_DIR / "uploads"
WEB_DIR = BASE_DIR / "web"
CONFIG_DIR = BASE_DIR / "config"
LLM_MODELS_CONFIG = CONFIG_DIR / "llm_models.json"


@dataclass
class Job:
    id: str
    status: str = "queued"
    logs: list[str] = field(default_factory=list)
    result: dict[str, Any] | None = None
    error: str | None = None
    created_at: str = field(default_factory=lambda: datetime.now().isoformat(timespec="seconds"))


app = FastAPI(title="Video Link To Transcript")
jobs: dict[str, Job] = {}

if WEB_DIR.exists():
    app.mount("/static", StaticFiles(directory=WEB_DIR), name="static")


def get_env_value(name: str) -> str | None:
    value = os.environ.get(name)
    if value:
        return value
    if os.name == "nt":
        try:
            import winreg

            with winreg.OpenKey(winreg.HKEY_CURRENT_USER, "Environment") as key:
                registry_value, _ = winreg.QueryValueEx(key, name)
                return registry_value or None
        except FileNotFoundError:
            return None
        except OSError:
            return None
    return None


def load_llm_model_config() -> dict[str, Any]:
    fallback = {
        "default": "mimo-v2.5",
        "models": [
            {
                "id": "mimo-v2.5",
                "label": "MiMo v2.5",
                "model": "mimo-v2.5",
                "base_url": get_env_value("MIMO_BASE_URL") or "https://token-plan-cn.xiaomimimo.com/v1",
                "api_key_env": "MIMO_API_KEY",
                "note": "Fallback preset generated by the app.",
            }
        ],
    }
    if not LLM_MODELS_CONFIG.exists():
        return fallback
    try:
        data = json.loads(LLM_MODELS_CONFIG.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise HTTPException(status_code=500, detail=f"Invalid config/llm_models.json: {error}") from error

    models = data.get("models")
    if not isinstance(models, list):
        raise HTTPException(status_code=500, detail="config/llm_models.json must contain a models list.")

    normalized_models: list[dict[str, str]] = []
    for index, model in enumerate(models, start=1):
        if not isinstance(model, dict):
            raise HTTPException(status_code=500, detail=f"LLM model preset #{index} must be an object.")
        model_name = str(model.get("model") or "").strip()
        if not model_name:
            raise HTTPException(status_code=500, detail=f"LLM model preset #{index} is missing model.")
        preset_id = str(model.get("id") or model_name).strip()
        normalized_models.append(
            {
                "id": preset_id,
                "label": str(model.get("label") or preset_id).strip(),
                "model": model_name,
                "base_url": str(model.get("base_url") or "").strip(),
                "api_key_env": str(model.get("api_key_env") or "LLM_API_KEY").strip(),
                "note": str(model.get("note") or "").strip(),
            }
        )
    if not normalized_models:
        raise HTTPException(status_code=500, detail="config/llm_models.json must contain at least one model preset.")

    default_id = str(data.get("default") or normalized_models[0]["id"]).strip()
    if not any(model["id"] == default_id for model in normalized_models):
        default_id = normalized_models[0]["id"]
    return {"default": default_id, "models": normalized_models}


def get_llm_preset(preset_id: str | None) -> dict[str, str] | None:
    config = load_llm_model_config()
    selected_id = preset_id or config["default"]
    for preset in config["models"]:
        if preset["id"] == selected_id:
            return preset
    return None


def path_to_item(path: Path | None) -> dict[str, str] | None:
    if not path:
        return None
    path = Path(path).resolve()
    return {
        "name": path.name,
        "path": str(path),
        "url": f"/files?path={path}",
    }


def result_to_response(result: dict[str, Any]) -> dict[str, Any]:
    transcripts = result.get("transcripts") or {}
    articles = result.get("articles") or {}
    return {
        "title": result.get("title"),
        "video": path_to_item(result.get("video")),
        "audio": path_to_item(result.get("audio")),
        "transcripts": {key: path_to_item(value) for key, value in transcripts.items()},
        "articles": {key: path_to_item(value) for key, value in articles.items()},
    }


def log_to(job: Job, message: str) -> None:
    job.logs.append(message)


async def run_job(job: Job, kwargs: dict[str, Any]) -> None:
    job.status = "running"
    try:
        result = await asyncio.to_thread(process_media, **kwargs, log=lambda message: log_to(job, message))
        job.result = result_to_response(result)
        job.status = "completed"
        log_to(job, "Done.")
    except SystemExit as error:
        job.error = str(error).strip() or "Task stopped."
        job.status = "failed"
        log_to(job, f"Failed: {job.error}")
    except Exception as error:
        job.error = str(error)
        job.status = "failed"
        log_to(job, f"Failed: {error}")


@app.get("/", response_class=HTMLResponse)
def index() -> FileResponse:
    return FileResponse(WEB_DIR / "index.html")


@app.get("/api/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


@app.get("/api/config/llm-models")
def llm_models() -> dict[str, Any]:
    return load_llm_model_config()


@app.post("/api/jobs")
async def create_job(
    url: str = Form(""),
    upload: UploadFile | None = File(None),
    source_type: str = Form("url"),
    save_video: bool = Form(False),
    save_audio: bool = Form(False),
    save_transcripts: bool = Form(False),
    generate_articles: bool = Form(False),
    article_styles: list[str] = Form([]),
    article_length: str = Form("long"),
    model: str = Form("small"),
    backend: str = Form("local"),
    mimo_api_key: str = Form(""),
    mimo_base_url: str = Form(""),
    mimo_model: str = Form("mimo-v2.5"),
    llm_preset: str = Form(""),
    llm_api_key: str = Form(""),
    llm_base_url: str = Form(""),
    llm_model: str = Form(""),
    language: str = Form("zh"),
    device: str = Form("cpu"),
    compute_type: str = Form("int8"),
    browser_download: bool = Form(True),
) -> dict[str, str]:
    if generate_articles:
        save_transcripts = True
    if not save_video and not save_audio and not save_transcripts:
        raise HTTPException(status_code=400, detail="Please select at least one output.")
    if backend not in {"local", "mimo"}:
        raise HTTPException(status_code=400, detail="Unsupported ASR backend.")

    job_id = uuid.uuid4().hex[:12]
    job = Job(id=job_id)
    jobs[job_id] = job

    input_file: Path | None = None
    source_url = extract_url(url) if url.strip() else None

    if source_type == "file":
        if not upload or not upload.filename:
            raise HTTPException(status_code=400, detail="Please choose a local video or audio file.")
        UPLOAD_DIR.mkdir(parents=True, exist_ok=True)
        input_file = UPLOAD_DIR / f"{job_id}_{Path(upload.filename).name}"
        with input_file.open("wb") as target:
            shutil.copyfileobj(upload.file, target)
        source_url = None
    elif not source_url:
        raise HTTPException(status_code=400, detail="Please paste a video URL.")

    llm_config = load_llm_model_config()
    llm_preset_data = get_llm_preset(llm_preset or llm_config["default"])
    if generate_articles and not llm_preset_data:
        raise HTTPException(status_code=400, detail="Selected writing model preset was not found.")

    preset_model = llm_preset_data["model"] if llm_preset_data else "mimo-v2.5"
    preset_base_url = llm_preset_data["base_url"] if llm_preset_data else ""
    preset_api_key_env = llm_preset_data["api_key_env"] if llm_preset_data else "LLM_API_KEY"

    kwargs = {
        "url": source_url,
        "input_file": input_file,
        "output_dir": OUTPUT_DIR,
        "model": model,
        "language": language or None,
        "device": device,
        "compute_type": compute_type,
        "backend": backend,
        "mimo_api_key": mimo_api_key.strip() or get_env_value("MIMO_API_KEY"),
        "mimo_base_url": mimo_base_url.strip() or get_env_value("MIMO_BASE_URL"),
        "mimo_model": mimo_model,
        "browser_download": browser_download,
        "browser_profile": BASE_DIR / "cookies" / "browser-profile",
        "browser_channel": "msedge",
        "save_video": save_video,
        "save_audio": save_audio,
        "save_transcripts": save_transcripts,
        "generate_article_outputs": generate_articles,
        "article_styles": article_styles or ["xiaohongshu", "professional"],
        "article_length": article_length if article_length in {"standard", "long", "deep"} else "long",
        "llm_api_key": (
            llm_api_key.strip()
            or get_env_value(preset_api_key_env)
            or get_env_value("LLM_API_KEY")
            or get_env_value("MIMO_API_KEY")
        ),
        "llm_base_url": llm_base_url.strip() or preset_base_url or get_env_value("LLM_BASE_URL") or get_env_value("MIMO_BASE_URL"),
        "llm_model": llm_model.strip() or preset_model or get_env_value("LLM_MODEL") or "mimo-v2.5",
    }

    asyncio.create_task(run_job(job, kwargs))
    return {"job_id": job_id}


@app.get("/api/jobs/{job_id}")
def get_job(job_id: str) -> dict[str, Any]:
    job = jobs.get(job_id)
    if not job:
        raise HTTPException(status_code=404, detail="Job not found.")
    return {
        "id": job.id,
        "status": job.status,
        "logs": job.logs,
        "result": job.result,
        "error": job.error,
        "created_at": job.created_at,
    }


@app.get("/api/files")
def list_files() -> dict[str, list[dict[str, str]]]:
    groups = {
        "videos": ("video", {".mp4", ".mkv", ".webm", ".mov"}),
        "audio": ("audio", {".m4a", ".mp3", ".wav", ".flac", ".ogg"}),
        "transcripts": ("transcripts", {".txt", ".srt", ".json"}),
        "articles": ("articles", {".md", ".txt", ".json"}),
    }
    response: dict[str, list[dict[str, str]]] = {}
    items_root = OUTPUT_DIR / "items"
    items_root.mkdir(parents=True, exist_ok=True)
    for key, (subdir, allowed_suffixes) in groups.items():
        files = sorted(
            (
                item
                for item in items_root.rglob("*")
                if item.is_file() and item.parent.name == subdir and item.suffix.lower() in allowed_suffixes
            ),
            key=lambda item: item.stat().st_mtime,
            reverse=True,
        )
        response[key] = [path_to_item(item) for item in files[:50] if path_to_item(item)]
    return response


@app.get("/files")
def download_file(path: str) -> FileResponse:
    requested = Path(path).resolve()
    allowed_roots = [OUTPUT_DIR.resolve()]
    if not any(requested == root or root in requested.parents for root in allowed_roots):
        raise HTTPException(status_code=403, detail="File is outside the outputs folder.")
    if not requested.exists() or not requested.is_file():
        raise HTTPException(status_code=404, detail="File not found.")
    return FileResponse(requested, filename=requested.name)
